# Generated by Django 5.1.6 on 2025-02-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_color_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='colorname',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
