# Generated by Django 5.1.6 on 2025-02-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_color_colorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hexcode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
