# Generated by Django 5.1.6 on 2025-02-20 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_color_hexcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
    ]
