# Generated by Django 5.1.6 on 2025-02-21 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.size'),
        ),
    ]
