# Generated by Django 5.1.6 on 2025-03-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_addtocart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addtocart',
            new_name='Cart',
        ),
    ]
