# Generated by Django 5.1.6 on 2025-03-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_register_image_register_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='number',
            field=models.IntegerField(max_length=15),
        ),
    ]
