# Generated by Django 5.1.6 on 2025-03-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_register_number_billingdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdetails',
            name='date',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='status',
        ),
    ]
